#!/bin/bash

# Check newest version
# * https://pypi.python.org/pypi/numpy
# * https://pypi.python.org/pypi/scipy
# * https://pypi.python.org/pypi/pandas
# * https://pypi.python.org/pypi/matplotlib
# * https://pypi.python.org/pypi/scikit-learn
# * https://github.com/numpy/numpy/tags
# * https://github.com/scipy/scipy/tags
# * https://github.com/pydata/pandas/tags
# * https://github.com/matplotlib/matplotlib/tags
# * https://github.com/scikit-learn/scikit-learn/tags

DST=`pwd`"/.build.py27/.local"
VERSION="2.7.9"

if ! [ -e $DST/bin/pyvenv ]; then
  pushd `pwd`
  echo ">>>>> Building Python"
  mkdir -p $DST
  mkdir -p .build.py27
  cd .build.py27
  wget https://www.python.org/ftp/python/${VERSION}/Python-${VERSION}.tgz
  tar zxvf Python-${VERSION}.tgz
  cd Python-${VERSION}
  ./configure --prefix $DST \
    --enable-shared \
    --with-ssl \
    LDFLAGS=-Wl,-rpath,$DST/lib && make && make install
  popd
fi

curl -kL https://bootstrap.pypa.io/get-pip.py | $DST/bin/python
[ $? -ne 0 ] && exit 1

$DST/bin/pip install virtualenv
[ $? -ne 0 ] && exit 1

$DST/bin/virtualenv venv.py27
source venv.py27/bin/activate

#$DST/bin/pyvenv venv
pip install numpy
[ $? -ne 0 ] && exit 1

pip install -r requirements.txt
[ $? -ne 0 ] && exit 1

# seaborn 0.6dev
pip install https://github.com/mwaskom/seaborn/archive/5debd4fb3793c0325c84616c8d79985d87a40b72.zip
[ $? -ne 0 ] && exit 1

# Lasagne (master on 2015-05-04)
pip install https://github.com/Lasagne/Lasagne/archive/0ba05a802df272a3c0264d50519d8edfff61fecc.zip
pip install 'nolearn>=0.5'
