#!/bin/bash

# Check newest version
# * https://pypi.python.org/pypi/numpy
# * https://pypi.python.org/pypi/scipy
# * https://pypi.python.org/pypi/pandas
# * https://pypi.python.org/pypi/matplotlib
# * https://pypi.python.org/pypi/scikit-learn
# * https://github.com/numpy/numpy/tags
# * https://github.com/scipy/scipy/tags
# * https://github.com/pydata/pandas/tags
# * https://github.com/matplotlib/matplotlib/tags
# * https://github.com/scikit-learn/scikit-learn/tags

DST=`pwd`"/.build/.local"
VERSION="3.4.3"

if ! [ -e $DST/bin/pyvenv ]; then
  pushd `pwd`
  echo ">>>>> Building Python"
  mkdir -p $DST
  mkdir -p .build
  cd .build
  wget https://www.python.org/ftp/python/${VERSION}/Python-${VERSION}.tgz
  tar zxvf Python-${VERSION}.tgz
  cd Python-${VERSION}
  ./configure --prefix $DST --enable-shared && make && make install
  popd
fi

$DST/bin/pyvenv venv
source venv/bin/activate
pip install numpy
[ $? -eq 0 ] && pip install -r requirements.txt

# seaborn 0.6dev
# pip install https://github.com/mwaskom/seaborn/archive/5debd4fb3793c0325c84616c8d79985d87a40b72.zip
